# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
